### ISSUE TITLE
Training crashes in Colab at the end of the epoch

### ISSUE THREAD

**Issue by eistakovskii** [dialogue-evaluation/RuCoCo-2023#5]
The training process crashes in Colab at the end of the epoch with the GPU accelerator turned on and the --max_batches_train set to 1 in the train.py arguments.
![image](https://user-images.githubusercontent.com/104836394/216316649-27b1cd46-5184-4309-8a33-8e4fb5c8812b.png)

**Comment by vdobrovolskii** [comment]
Thanks!

The issue is related to the way Google Colab handles near-OOM events. The problem is caused by `ModelCheckpoint` requiring too much RAM on checkpoint saving.

The following solutions are available:
1. Reduce memory consumption of `ModelCheckpoint` by setting `save_weights_only=True` in [train:65](https://github.com/dialogue-evaluation/RuCoCo-2023/blob/main/baseline/train.py#L65). This has the undesired effect of not being able to continue training from resulting checkpoints.
2. Override the IO plugin. For this, in [train.py](https://github.com/dialogue-evaluation/RuCoCo-2023/blob/main/baseline/train.py) create the following class:
    ```
    class BasicCheckpointIO(pl.plugins.io.TorchCheckpointIO):
        def save_checkpoint(self, checkpoint, path, storage_options=None):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            torch.save(checkpoint, path)
    ```
    Then pass it to the Trainer initialization in [train.py:72](https://github.com/dialogue-evaluation/RuCoCo-2023/blob/main/baseline/train.py#L72): `plugins=[BasicCheckpointIO()]`.
